# Site settings
title: Grupo MATE
email: ferragut@ort.edu.uy
description: Mathematics Applied to Telecommunications and Energy
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Mathematics Applied to Telecommunications and Energy Research Group

location: >
  Universidad ORT Uruguay, Facultad de Ingeniería, Montevideo,Uruguay

contact: >
  <a href="mailto:ferragut@ort.edu.uy" target="_blank">Contact us <i class="fa fa-envelope fa-1x"></i></a>

# Pages shown in navbar
nav_pages:
#  - name: about
  - name: team
  - name: publications
#  - name: talks
  - name: research
#  - name: software
  - name: teaching
#  - name: blogs

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Ferragut
  first_name: [Andres]

  style: citesty
  locale: en

  source: /assets
  bibliography: papers.bib
  bibliography_template: bib
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
